### ISSUE TITLE
Windows 10 daily file is created with UNIX line endings - how to create with dos line endings \n\r via configuration file

### ISSUE THREAD

**Issue by rynes** [dkaslovsky/textnote#7]

**Comment by rynes** [comment]
0000000000     [   W   e   d   ]       0   3       M   a   r       2   0   2
0000000020     1  \n  \n  \n  \n   _   _   _   T   O   D   O   _   _   _  \n
0000000040     1   .       t   h   i   s       i   s       s   o   m   e   t
0000000060     h   i   n   g  \n  \n  \n  \n   _   _   _   D   O   N   E   _
0000000100     _   _  \n  \n  \n  \n   _   _   _   N   O   T   E   S   _   _
0000000120     _  \n  \n  \n  \n
0000000125

**Comment by dkaslovsky** [comment]
Thank you for opening this issue.  Would you be able to provide a bit more information?  In particular, the following would be helpful:
- Which version of textnote are you using? `textnote --version`
- Is the `$EDITOR` environment variable set and if so what is it set to?
- Do the files render correctly in the editor you are using?
- Can you provide a bit more clarity with respect to the issue you are having?  Is it simply a request that all newline characters can be configured to be `\n\r` instead of `\n`?  I have to admit that I have no experience in a Windows environment and am unsure if this request is unique to the editor or shell you are using, or if it is globally necessary for Windows.  Any insight you can provide will help my understanding.

Thanks again for taking the time to open this issue.

**Comment by rynes** [comment]
a) textnote version v1.0.0
b) %EDITOR% not set, I tried these values, but none made a difference:
a. “set EDITOR=gvim”,
b. “set EDITOR=C:\WINDWS\gvim.bat”,
c. “set EDITOR=C:\Users\Philip\Downloads\Shareware\Gvim\vim\vim82\gvim.exe
c) Files render ok in my editor, gvim.exe version 8.2 for Windows 32bit, see below for more version information.
I found a workaround. There is a program unix2dos.exe that converts line endings. So you can close the issue.

**Comment by dkaslovsky** [comment]
Thanks for sharing the information.  I'm glad you found a solution that works, and am very glad that you are giving textnote a try!  If it is helpful, the latest version (v1.1.1) does respect the `$EDITOR` environment variable so that textnote will open notes in your editor of choice.  Thanks again for contributing the issue, I'll go ahead and close it as you've indicated.
